services:
    knp_rad_user.event_listener.odm.password_hash_listener:
        class:   Knp\Rad\User\EventListener\ODM\PasswordHashListener
        public:  false
        arguments:
            - @knp_rad_user.event_listener.persistence.password_hash_listener
        tags:
            - { name: doctrine_mongodb.odm.event_listener,  event: prePersist,  method: prePersist,  priority: 100 }
            - { name: doctrine_couchdb.event_listener,      event: prePersist,  method: prePersist,  priority: 100 }
            - { name: doctrine_mongodb.odm.event_listener,  event: preUpdate,   method: preUpdate }
            - { name: doctrine_couchdb.event_listener,      event: preUpdate,   method: preUpdate }

    knp_rad_user.event_listener.persistence.password_generation_listener:
        class:   Knp\Rad\User\EventListener\Persistence\PasswordGenerationListener
        public:  false
        tags:
            - { name: doctrine.event_listener,              event: prePersist,  method: prePersist,  priority: 200 }
            - { name: doctrine_mongodb.odm.event_listener,  event: prePersist,  method: prePersist,  priority: 200 }
            - { name: doctrine_couchdb.event_listener,      event: prePersist,  method: prePersist,  priority: 200 }

    knp_rad_user.event_listener.persistence.password_hash_listener:
        class:   Knp\Rad\User\EventListener\Persistence\PasswordHashListener
        public:  false
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine.event_listener,              event: prePersist,  method: prePersist,  priority: 100 }
            - { name: doctrine.event_listener,              event: preUpdate,   method: preUpdate }

    knp_rad_user.event_listener.persistence.salt_generation_listener:
        class:   Knp\Rad\User\EventListener\Persistence\SaltGenerationListener
        public:  false
        lazy:    true
        tags:
            - { name: doctrine.event_listener,              event: prePersist,  method: prePersist,  priority: 200 }
            - { name: doctrine_mongodb.odm.event_listener,  event: prePersist,  method: prePersist,  priority: 200 }
            - { name: doctrine_couchdb.event_listener,      event: prePersist,  method: prePersist,  priority: 200 }

