services:
    knp_rad_user.event_listener.password_generation_listener:
        class: Knp\Rad\User\EventListener\PasswordGenerationListener
        public: false

    knp_rad_user.event_listener.password_hash_listener:
        class: Knp\Rad\User\EventListener\PasswordHashListener
        public: false
        arguments:
            - @security.encoder_factory

    knp_rad_user.event_listener.salt_generation_listener:
        class: Knp\Rad\User\EventListener\SaltGenerationListener
        public: false
